Multipage Surveys
Watts-Lab/surveyor pull request #40
Opened 2021-11-01 10:20 UTC by KaranSampath

Working on ensuring that the numbering of questions works properly. The rest of the implementation should be correct.

2021-11-01 12:46 UTC, markwhiting commented
@KaranSampath looks good overall. Assign me as a reviewer once you're ready for that. 

Also I notice that the failing test (`Missing CSRF middleware`) is requesting we add back CSRF. @sumants-dev or @KaranSampath I thought we had left it out because it is now built in to Express, but perhaps we should explicitly put it back?

2021-11-01 15:10 UTC, sumants-dev commented
I removed it because it added some complications. I added it back. @KaranSampath  If you have question how it works, DM me, I can go into it.

@KaranSampath  Also, the final page submission doesn't seem to work. On the last page of the survey for both paged and multipage. It just returns to the survey. You need to add this commented part back for the last page submission.

``` // if (admin) {
  //   res.render("thanks", {
  //     code: JSON.stringify(req.body, null, 2),
  //     admin: admin,
  //   });
  // } else res.redirect("/"); // Needs to be updated to deal with multiple page surveys```

2021-11-01 15:15 UTC, markwhiting commented
Thanks @sumants-dev and makes sense re CSRF.

2021-11-01 15:19 UTC, KaranSampath commented
Ah, thanks for pointing out 1, didn't see that and will get that fixed.

On 2, I thought about adding next but realized that since workers aren't going to be able to access previous pages it may be slightly misleading for them. Won't just a submit make it clear that these answers couldn't be changed later on?

2021-11-01 15:25 UTC, markwhiting commented
If you're thinking about how to make it more clear that people can't go back, perhaps we do something like "Submit page x of y"?

2021-11-15 18:16 UTC, KaranSampath commented
@sumants-dev I'm slightly unsure how to fix the submission issue, it seems my conditionals aren't working and I'm unsure why. Could you please take a quick look at it? Thanks!

Have fixed the other issues.

2021-11-15 20:12 UTC, sumants-dev commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->You forgot to pipe the variables of check and final in survey.pug. From my testing it was fixed. Check on your end also. Best,Sumant From: Karan SampathSent: Monday, November 15, 2021 1:16 PMTo: Watts-Lab/surveyorCc: Sumant R Shringari; MentionSubject: Re: [Watts-Lab/surveyor] Multipage Surveys (PR ***@***.*** I'm slightly unsure how to fix the submission issue, it seems my conditionals aren't working and I'm unsure why. Could you please take a quick look at it? Thanks!Have fixed the other issues.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

2021-11-16 19:41 UTC, KaranSampath commented
Tested and fixed numbering. The rendering of the survey looks different so let me know if that's okay otherwise I think the PR is ready to merge @markwhiting.

2021-11-17 22:11 UTC, markwhiting requested changes
Overall looks great. I just think we could have a minor tweak to get the question format more consistent but otherwise seems good to go.

2021-11-17 22:11 UTC, markwhiting commented on views/survey.pug
> +                li(class='inputBlock')= start++
might be better to put this number as part of the h4 so it doesn't wrap lines. Also trail with a `.`, so it looks like a number. 

e.g., 
> 3. Select the word that best describes what the person in the picture is thinking or feeling

2021-11-19 02:56 UTC, markwhiting approved these changes
👍

2021-11-19 02:56 UTC, merged